export const ARTISTS = [
  { id: 1,  name: "Isabella Hart",    location: "New York, US",   medium: ["portraits","oil pastels"],    followers: "12.4k", price: 2500, rating: 4.9, available: true,  avatar: "https://i.pravatar.cc/80?img=1",  cover: "portrait1",  bio: "Award-winning portrait artist specialising in realistic oil paintings and fine-art commissions. My work explores the depth of human emotion through light and shadow." },
  { id: 2,  name: "Thomas Blackwell", location: "London, UK",     medium: ["charcoal sketch","portraits"], followers: "18.7k", price: 3200, rating: 4.8, available: true,  avatar: "https://i.pravatar.cc/80?img=3",  cover: "charcoal1",  bio: "Classical charcoal artist with a focus on portraiture and figurative work. Available for bespoke commissions and gallery collaborations." },
  { id: 3,  name: "Yuki Tanaka",      location: "Tokyo, Japan",   medium: ["watercolours","origami"],      followers: "9.8k",  price: 2000, rating: 4.7, available: true,  avatar: "https://i.pravatar.cc/80?img=5",  cover: "water1",     bio: "Japanese watercolour artist blending traditional techniques with contemporary aesthetics. Specialising in botanical and landscape compositions." },
  { id: 4,  name: "Marco Rivera",     location: "Barcelona, ES",  medium: ["graffiti","acrylic paint"],    followers: "31.2k", price: 4500, rating: 5.0, available: false, avatar: "https://i.pravatar.cc/80?img=7",  cover: "graffiti1",  bio: "Internationally recognised street artist and muralist. My large-scale works transform public spaces into vibrant cultural landmarks." },
  { id: 5,  name: "Anika Patel",      location: "Mumbai, IN",     medium: ["oil pastels","portraits"],     followers: "7.1k",  price: 1800, rating: 4.6, available: true,  avatar: "https://i.pravatar.cc/80?img=9",  cover: "oil1",       bio: "Vibrant oil pastel artist drawing inspiration from Indian culture and everyday life. Open for portrait and editorial commissions." },
  { id: 6,  name: "Lucas Müller",     location: "Berlin, DE",     medium: ["metal work","ceramics"],       followers: "14.5k", price: 3800, rating: 4.8, available: true,  avatar: "https://i.pravatar.cc/80?img=11", cover: "metal1",     bio: "Sculptor and craftsman working in metal and ceramic. Each piece is hand-finished and carries a unique story rooted in industrial heritage." },
  { id: 7,  name: "Sofia Andersen",   location: "Copenhagen, DK", medium: ["ceramics","watercolours"],     followers: "6.3k",  price: 2200, rating: 4.5, available: true,  avatar: "https://i.pravatar.cc/80?img=13", cover: "ceramic1",   bio: "Scandinavian ceramicist and watercolourist. My practice centres on the beauty of imperfection and the dialogue between form and function." },
  { id: 8,  name: "James Okafor",     location: "Lagos, NG",      medium: ["acrylic paint","portraits"],   followers: "22.9k", price: 2900, rating: 4.9, available: false, avatar: "https://i.pravatar.cc/80?img=15", cover: "acrylic1",   bio: "Afro-contemporary painter whose bold acrylics celebrate African identity and diaspora narratives. Exhibited across Lagos, London and New York." },
  { id: 9,  name: "Elena Sousa",      location: "Lisbon, PT",     medium: ["pencil colours","origami"],    followers: "5.4k",  price: 1500, rating: 4.4, available: true,  avatar: "https://i.pravatar.cc/80?img=17", cover: "pencil1",    bio: "Coloured-pencil illustrator and origami artist creating intricate, meditative works. Commissions open for editorial and personal pieces." },
  { id: 10, name: "Kai Nakamura",     location: "Osaka, Japan",   medium: ["origami","charcoal sketch"],   followers: "11.0k", price: 2600, rating: 4.7, available: true,  avatar: "https://i.pravatar.cc/80?img=19", cover: "origami1",   bio: "Origami master and charcoal illustrator merging precision paper-folding with expressive drawing. Workshop instructor and published artist." },
  { id: 11, name: "Priya Sharma",     location: "Delhi, IN",      medium: ["watercolours","oil pastels"],  followers: "8.8k",  price: 2100, rating: 4.6, available: true,  avatar: "https://i.pravatar.cc/80?img=21", cover: "water2",     bio: "Delhi-based watercolourist and pastel artist capturing the colours and chaos of urban India. Available for editorial and commercial briefs." },
  { id: 12, name: "Diego Flores",     location: "Mexico City",    medium: ["graffiti","acrylic paint"],    followers: "19.3k", price: 3100, rating: 4.8, available: true,  avatar: "https://i.pravatar.cc/80?img=23", cover: "graffiti2",  bio: "Muralist and acrylic painter inspired by Latin American folklore and street culture. Open to mural, canvas, and brand collaboration projects." },
];

export type Artist = typeof ARTISTS[number];
